channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7.3
  - c-compiler=1.0.4
  - cmake=3.14.0
  - qt=5.12.5  # conda-forge does not have 5.13.2 available
  - mpi4py=3.0.3
  - cudatoolkit=10.0
  - ipython
  - pip
  - pip:
    - gym3==0.3.3
    - numpy==1.17.2
    - gym==0.15.4
    - filelock==3.0.10
    - tensorflow==1.15.0
    - pytest # for baselines
    - joblib
    - ipdb
    - matplotlib
